### ISSUE TITLE
Error when scanning for up and vuln host

### ISSUE THREAD

**Issue by alqassam1998** [M0tHs3C/Hikxploit#4]
This happens everytime I try to scan "up" and "vuln" hosts after got the host list from shodan.
```
[#]Select an option:3
[+]Loading all host...
Traceback (most recent call last):
  File "hikxploit_win.py", line 351, in <module>
    main()
  File "hikxploit_win.py", line 348, in main
    response()
  File "hikxploit_win.py", line 311, in response
    response()
  File "hikxploit_win.py", line 316, in response
    scan()
  File "hikxploit_win.py", line 289, in scan
    up_scan()
  File "hikxploit_win.py", line 242, in up_scan
    target_host = match1.group()
AttributeError: 'NoneType' object has no attribute 'group'
```

An error that appears when scanning for vuln hosts
```
[#]Select an option:4
[##]Checking Traceback (most recent call last):
  File "hikxploit_win.py", line 351, in <module>
    main()
  File "hikxploit_win.py", line 348, in main
    response()
  File "hikxploit_win.py", line 311, in response
    response()
  File "hikxploit_win.py", line 317, in response
    response()
  File "hikxploit_win.py", line 319, in response
    vuln_scan_exp()
  File "hikxploit_win.py", line 272, in vuln_scan_exp
    response = requests.get('http://'+ip_to_check+'/security/users/1?'+ BackdoorAuthArg)
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\HanifFurqonHidayat\Anaconda2\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL u'http:///security/users/1?auth=YWRtaW46MTEK': No host supplied
```

**Comment by M0tHs3C** [comment]
this tool is deprecated, the project moved to argo
im closing the issue

**Comment by alqassam1998** [comment]
Ok thanks
